version: '3.5'

volumes:
  redis:
    driver: local

services:
  application:
    restart: unless-stopped
    container_name: app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
    image: application
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 3000:3000
    command: npm run watch
  redis:
    restart: unless-stopped
    container_name: redis
    image: redis:6-alpine
    # volumes:
    #   - redis:/data